### ISSUE TITLE
Disabling a single command is not working

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.az#29]
Following this [doc](https://github.com/Azure/autorest.az/blob/master/doc/01-authoring-azure-cli-commands-v1.md#disabling-command-groups), I tried to disable a single command such as `blueprint artifact update`:
```
  cmd-override:
    "^.*blueprint artifact update.*$": "-" 
```
But it does not work.
Disabling the whole command group `blueprint artifact` works well:
```
  cmd-override:
    "^.*blueprint artifact.*$": "-" 
```

**Comment by MyronFanQiu** [comment]
I tried to rename the command and failed too.
```
  cmd-override:
    "^powerbiembedded$": "* powerbi"
```

**Comment by MyronFanQiu** [comment]
look like I cannot rename `az something` to `az anotherthing`

**Comment by zikalino** [comment]
this should work now, pls check, and let me know if you have any problem

**Comment by MyronFanQiu** [comment]
@zikalino Looks like we still cannot rename a command. We can disable it now.
